/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Tgm.Roborally.Api.Client;
using Tgm.Roborally.Api.Api;
using Tgm.Roborally.Api.Model;

namespace Tgm.Roborally.Api.Test
{
    /// <summary>
    ///  Class for testing ConsumerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConsumerApiTests : IDisposable
    {
        private ConsumerApi instance;

        public ConsumerApiTests()
        {
            instance = new ConsumerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsumerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ConsumerApi
            //Assert.IsType(typeof(ConsumerApi), instance, "instance is a ConsumerApi");
        }

        
        /// <summary>
        /// Test RegisterConsumer
        /// </summary>
        [Fact]
        public void RegisterConsumerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int gameId = null;
            //ConsumerRegistration consumerRegistration = null;
            //var response = instance.RegisterConsumer(gameId, consumerRegistration);
            //Assert.IsType<JoinResponse> (response, "response is JoinResponse");
        }
        
    }

}
