/*
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v2.9.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tgm.Roborally.Api.Client.OpenAPIDateConverter;

namespace Tgm.Roborally.Api.Model
{
    /// <summary>
    /// Describes what the event is about
    /// </summary>
    /// <value>Describes what the event is about</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EventType
    {
        /// <summary>
        /// Enum Movement for value: movement
        /// </summary>
        [EnumMember(Value = "movement")]
        Movement = 1,

        /// <summary>
        /// Enum UpgradePurchase for value: upgrade purchase
        /// </summary>
        [EnumMember(Value = "upgrade purchase")]
        UpgradePurchase = 2,

        /// <summary>
        /// Enum ActivateUpgrade for value: activate upgrade
        /// </summary>
        [EnumMember(Value = "activate upgrade")]
        ActivateUpgrade = 3,

        /// <summary>
        /// Enum LazerShot for value: lazer shot
        /// </summary>
        [EnumMember(Value = "lazer shot")]
        LazerShot = 4,

        /// <summary>
        /// Enum GameStart for value: game start
        /// </summary>
        [EnumMember(Value = "game start")]
        GameStart = 5,

        /// <summary>
        /// Enum ClearShop for value: clear shop
        /// </summary>
        [EnumMember(Value = "clear shop")]
        ClearShop = 6,

        /// <summary>
        /// Enum FillShop for value: fill shop
        /// </summary>
        [EnumMember(Value = "fill shop")]
        FillShop = 7,

        /// <summary>
        /// Enum ProgrammingTimerStart for value: programming timer start
        /// </summary>
        [EnumMember(Value = "programming timer start")]
        ProgrammingTimerStart = 8,

        /// <summary>
        /// Enum ProgrammingTimerStop for value: programming timer stop
        /// </summary>
        [EnumMember(Value = "programming timer stop")]
        ProgrammingTimerStop = 9,

        /// <summary>
        /// Enum RandomCardDistribution for value: random card distribution
        /// </summary>
        [EnumMember(Value = "random card distribution")]
        RandomCardDistribution = 10,

        /// <summary>
        /// Enum TakeCardEvent for value: take card event
        /// </summary>
        [EnumMember(Value = "take card event")]
        TakeCardEvent = 11,

        /// <summary>
        /// Enum ActivateCheckpoint for value: activate checkpoint
        /// </summary>
        [EnumMember(Value = "activate checkpoint")]
        ActivateCheckpoint = 12,

        /// <summary>
        /// Enum GamePhaseChanged for value: game_phase_changed
        /// </summary>
        [EnumMember(Value = "game_phase_changed")]
        GamePhaseChanged = 13,

        /// <summary>
        /// Enum GameRoundPhaseChanged for value: game_round_phase_changed
        /// </summary>
        [EnumMember(Value = "game_round_phase_changed")]
        GameRoundPhaseChanged = 14,

        /// <summary>
        /// Enum Pause for value: pause
        /// </summary>
        [EnumMember(Value = "pause")]
        Pause = 15,

        /// <summary>
        /// Enum Unpause for value: unpause
        /// </summary>
        [EnumMember(Value = "unpause")]
        Unpause = 16,

        /// <summary>
        /// Enum Damage for value: damage
        /// </summary>
        [EnumMember(Value = "damage")]
        Damage = 17,

        /// <summary>
        /// Enum LazerHit for value: lazer hit
        /// </summary>
        [EnumMember(Value = "lazer hit")]
        LazerHit = 18,

        /// <summary>
        /// Enum Push for value: push
        /// </summary>
        [EnumMember(Value = "push")]
        Push = 19,

        /// <summary>
        /// Enum Join for value: join
        /// </summary>
        [EnumMember(Value = "join")]
        Join = 20,

        /// <summary>
        /// Enum LockIn for value: lock in
        /// </summary>
        [EnumMember(Value = "lock in")]
        LockIn = 21,

        /// <summary>
        /// Enum RobotStartExecuting for value: robot_start_executing
        /// </summary>
        [EnumMember(Value = "robot_start_executing")]
        RobotStartExecuting = 22,

        /// <summary>
        /// Enum Heal for value: heal
        /// </summary>
        [EnumMember(Value = "heal")]
        Heal = 23,

        /// <summary>
        /// Enum EnergyGain for value: energy gain
        /// </summary>
        [EnumMember(Value = "energy gain")]
        EnergyGain = 24,

        /// <summary>
        /// Enum Map for value: map
        /// </summary>
        [EnumMember(Value = "map")]
        Map = 25,

        /// <summary>
        /// Enum Shutdown for value: shutdown
        /// </summary>
        [EnumMember(Value = "shutdown")]
        Shutdown = 26,

        /// <summary>
        /// Enum ChangeRegister for value: change register
        /// </summary>
        [EnumMember(Value = "change register")]
        ChangeRegister = 27,

        /// <summary>
        /// Enum GameEndEvent for value: game end event
        /// </summary>
        [EnumMember(Value = "game end event")]
        GameEndEvent = 28,

        /// <summary>
        /// Enum ClearRegister for value: clear register
        /// </summary>
        [EnumMember(Value = "clear register")]
        ClearRegister = 29,

        /// <summary>
        /// Enum TimeElapsed for value: time elapsed
        /// </summary>
        [EnumMember(Value = "time elapsed")]
        TimeElapsed = 30,

        /// <summary>
        /// Enum MapCreated for value: map created
        /// </summary>
        [EnumMember(Value = "map created")]
        MapCreated = 31,

        /// <summary>
        /// Enum UpgradesDiscarded for value: upgrades discarded
        /// </summary>
        [EnumMember(Value = "upgrades discarded")]
        UpgradesDiscarded = 32

    }

}
