/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v2.14.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tgm.Roborally.Api.Client.OpenAPIDateConverter;

namespace Tgm.Roborally.Api.Model
{
    /// <summary>
    /// the type of a robot
    /// </summary>
    /// <value>the type of a robot</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Robots
    {
        /// <summary>
        /// Enum Tank for value: tank
        /// </summary>
        [EnumMember(Value = "tank")]
        Tank = 1,

        /// <summary>
        /// Enum Drone for value: drone
        /// </summary>
        [EnumMember(Value = "drone")]
        Drone = 2,

        /// <summary>
        /// Enum Bulldozer for value: bulldozer
        /// </summary>
        [EnumMember(Value = "bulldozer")]
        Bulldozer = 3,

        /// <summary>
        /// Enum Turtle for value: turtle
        /// </summary>
        [EnumMember(Value = "turtle")]
        Turtle = 4,

        /// <summary>
        /// Enum WallE for value: wallE
        /// </summary>
        [EnumMember(Value = "wallE")]
        WallE = 5,

        /// <summary>
        /// Enum Robot for value: robot
        /// </summary>
        [EnumMember(Value = "robot")]
        Robot = 6,

        /// <summary>
        /// Enum Mech for value: mech
        /// </summary>
        [EnumMember(Value = "mech")]
        Mech = 7

    }

}
