/*
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v2.9.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tgm.Roborally.Api.Client.OpenAPIDateConverter;

namespace Tgm.Roborally.Api.Model
{
    /// <summary>
    /// The rotator blocks consist of 4 blocks. This 4 blocks can be differenciated by this property
    /// </summary>
    /// <value>The rotator blocks consist of 4 blocks. This 4 blocks can be differenciated by this property</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RotatorPosition
    {
        /// <summary>
        /// Enum UpLeft for value: up_left
        /// </summary>
        [EnumMember(Value = "up_left")]
        UpLeft = 1,

        /// <summary>
        /// Enum UpRight for value: up_right
        /// </summary>
        [EnumMember(Value = "up_right")]
        UpRight = 2,

        /// <summary>
        /// Enum DownLeft for value: down_left
        /// </summary>
        [EnumMember(Value = "down_left")]
        DownLeft = 3,

        /// <summary>
        /// Enum DownRight for value: down_right
        /// </summary>
        [EnumMember(Value = "down_right")]
        DownRight = 4

    }

}
