/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v0.9.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tgm.Roborally.Api.Api;
using Tgm.Roborally.Api.Model;
using Tgm.Roborally.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tgm.Roborally.Api.Test
{
    /// <summary>
    ///  Class for testing DrawCardEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DrawCardEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DrawCardEvent
        //private DrawCardEvent instance;

        public DrawCardEventTests()
        {
            // TODO uncomment below to create an instance of DrawCardEvent
            //instance = new DrawCardEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DrawCardEvent
        /// </summary>
        [Fact]
        public void DrawCardEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DrawCardEvent
            //Assert.IsInstanceOfType<DrawCardEvent> (instance, "variable 'instance' is a DrawCardEvent");
        }


        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Fact]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Cards'
        /// </summary>
        [Fact]
        public void CardsTest()
        {
            // TODO unit test for the property 'Cards'
        }

    }

}
