/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v0.9.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tgm.Roborally.Api.Api;
using Tgm.Roborally.Api.Model;
using Tgm.Roborally.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tgm.Roborally.Api.Test
{
    /// <summary>
    ///  Class for testing GamePhaseChangedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GamePhaseChangedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GamePhaseChangedEvent
        //private GamePhaseChangedEvent instance;

        public GamePhaseChangedEventTests()
        {
            // TODO uncomment below to create an instance of GamePhaseChangedEvent
            //instance = new GamePhaseChangedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GamePhaseChangedEvent
        /// </summary>
        [Fact]
        public void GamePhaseChangedEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GamePhaseChangedEvent
            //Assert.IsInstanceOfType<GamePhaseChangedEvent> (instance, "variable 'instance' is a GamePhaseChangedEvent");
        }


        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Fact]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }
        /// <summary>
        /// Test the property 'Step'
        /// </summary>
        [Fact]
        public void StepTest()
        {
            // TODO unit test for the property 'Step'
        }
        /// <summary>
        /// Test the property 'Information'
        /// </summary>
        [Fact]
        public void InformationTest()
        {
            // TODO unit test for the property 'Information'
        }

    }

}
