name: .NET build

on:
  label:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create package
      run: dotnet pack
    - name: Create Release
      uses: ncipollo/release-action@v1.8.4
      with:
        artifacts: src/Tgm.Roborally.Api/bin/Debug/*.nupkg,src/Tgm.Roborally.Api/bin/Debug/netcoreapp3.0/*.dll
        prerelease: true
      
